version: '3.5'
services:
  # overrides for e2e tests to be closer to production
  # use with command:
  # docker-compose -f docker-compose.yaml -f docker-compose.e2e.yml up -d --build

  front:
    image: 'wa-front-e2e'
    build:
      context: ./
      dockerfile: front/Dockerfile
    command: /bin/sh -c "/templater.sh && envsubst < /usr/share/nginx/html/env-config.template.js > /usr/share/nginx/html/env-config.js && exec nginx -g 'daemon off;'"
    volumes: []

  pusher:
    image: 'wa-pusher-e2e'
    build:
      context: ./
      dockerfile: pusher/Dockerfile
    command: yarn run runprod
    volumes: []

  back:
    image: 'wa-back-e2e'
    build:
      context: ./
      dockerfile: back/Dockerfile
    command: yarn run runprod
    volumes: []
